/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_NativeService */

#ifndef _Included_ru_nsu_NativeService
#define _Included_ru_nsu_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_NativeService
 * Method:    crashTheProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_crashTheProcess
  (JNIEnv *, jobject);

/*
 * Class:     ru_nsu_NativeService
 * Method:    allocate1KbMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_allocate1KbMemory
  (JNIEnv *, jobject);

/*
 * Class:     ru_nsu_NativeService
 * Method:    chainOfCalls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_chainOfCalls
  (JNIEnv *, jobject);

/*
 * Class:     ru_nsu_NativeService
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_nsu_NativeService_getStringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_nsu_NativeService
 * Method:    callObjectMethod
 * Signature: (Lru/nsu/Bean;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_callObjectMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ru_nsu_NativeService
 * Method:    modifyObjectField
 * Signature: (Lru/nsu/Bean;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_modifyObjectField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ru_nsu_NativeService
 * Method:    createNativeStruct
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ru_nsu_NativeService_createNativeStruct
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ru_nsu_NativeService
 * Method:    getValueFromNativeStruct
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ru_nsu_NativeService_getValueFromNativeStruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_nsu_NativeService
 * Method:    freeNativeStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_NativeService_freeNativeStruct
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
